// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KirkDiggler/ronnied/internal/dice (interfaces: Roller)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=mocks/mock_roller.go github.com/KirkDiggler/ronnied/internal/dice Roller
//
// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRoller is a mock of Roller interface.
type MockRoller struct {
	ctrl     *gomock.Controller
	recorder *MockRollerMockRecorder
}

// MockRollerMockRecorder is the mock recorder for MockRoller.
type MockRollerMockRecorder struct {
	mock *MockRoller
}

// NewMockRoller creates a new mock instance.
func NewMockRoller(ctrl *gomock.Controller) *MockRoller {
	mock := &MockRoller{ctrl: ctrl}
	mock.recorder = &MockRollerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoller) EXPECT() *MockRollerMockRecorder {
	return m.recorder
}

// Roll mocks base method.
func (m *MockRoller) Roll(arg0 int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Roll", arg0)
	ret0, _ := ret[0].(int)
	return ret0
}

// Roll indicates an expected call of Roll.
func (mr *MockRollerMockRecorder) Roll(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Roll", reflect.TypeOf((*MockRoller)(nil).Roll), arg0)
}
