// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KirkDiggler/ronnied/internal/repositories/game (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=mocks/mock_repository.go github.com/KirkDiggler/ronnied/internal/repositories/game Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/KirkDiggler/ronnied/internal/models"
	game "github.com/KirkDiggler/ronnied/internal/repositories/game"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// DeleteGame mocks base method.
func (m *MockRepository) DeleteGame(ctx context.Context, input *game.DeleteGameInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGame", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGame indicates an expected call of DeleteGame.
func (mr *MockRepositoryMockRecorder) DeleteGame(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGame", reflect.TypeOf((*MockRepository)(nil).DeleteGame), ctx, input)
}

// GetActiveGames mocks base method.
func (m *MockRepository) GetActiveGames(ctx context.Context, input *game.GetActiveGamesInput) (*game.GetActiveGamesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveGames", ctx, input)
	ret0, _ := ret[0].(*game.GetActiveGamesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveGames indicates an expected call of GetActiveGames.
func (mr *MockRepositoryMockRecorder) GetActiveGames(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveGames", reflect.TypeOf((*MockRepository)(nil).GetActiveGames), ctx, input)
}

// GetGame mocks base method.
func (m *MockRepository) GetGame(ctx context.Context, input *game.GetGameInput) (*models.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGame", ctx, input)
	ret0, _ := ret[0].(*models.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGame indicates an expected call of GetGame.
func (mr *MockRepositoryMockRecorder) GetGame(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGame", reflect.TypeOf((*MockRepository)(nil).GetGame), ctx, input)
}

// GetGameByChannel mocks base method.
func (m *MockRepository) GetGameByChannel(ctx context.Context, input *game.GetGameByChannelInput) (*models.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGameByChannel", ctx, input)
	ret0, _ := ret[0].(*models.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGameByChannel indicates an expected call of GetGameByChannel.
func (mr *MockRepositoryMockRecorder) GetGameByChannel(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGameByChannel", reflect.TypeOf((*MockRepository)(nil).GetGameByChannel), ctx, input)
}

// SaveGame mocks base method.
func (m *MockRepository) SaveGame(ctx context.Context, input *game.SaveGameInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveGame", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveGame indicates an expected call of SaveGame.
func (mr *MockRepositoryMockRecorder) SaveGame(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveGame", reflect.TypeOf((*MockRepository)(nil).SaveGame), ctx, input)
}
